// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using armadieti2.Models;

#nullable disable

namespace armadieti2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250228154055_db models")]
    partial class dbmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("armadieti2.Models.ArmadioModel", b =>
                {
                    b.Property<int>("IdArmadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArmadio"));

                    b.Property<string>("CategoriaArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Piano")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatoArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdArmadio");

                    b.HasIndex("CategoriaArmadio");

                    b.HasIndex("StatoArmadio");

                    b.ToTable("ArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.CategoriaArmadioModel", b =>
                {
                    b.Property<string>("CategoriaArmadio")
                        .HasColumnType("text");

                    b.HasKey("CategoriaArmadio");

                    b.ToTable("CategoriaArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.ChiaveModel", b =>
                {
                    b.Property<int>("IdChiave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChiave"));

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArmadio")
                        .HasColumnType("integer");

                    b.Property<string>("StatoChiave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdChiave");

                    b.HasIndex("IdArmadio");

                    b.HasIndex("StatoChiave");

                    b.ToTable("ChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.DipartimentoModel", b =>
                {
                    b.Property<string>("NomeDipartimento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NomeDipartimento");

                    b.ToTable("DipartimentoModel");
                });

            modelBuilder.Entity("armadieti2.Models.NoleggioModel", b =>
                {
                    b.Property<int>("IdNoleggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNoleggio"));

                    b.Property<decimal>("Cauzione")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArmadio")
                        .HasColumnType("integer");

                    b.Property<int>("IdChiave")
                        .HasColumnType("integer");

                    b.Property<int>("IdUtente")
                        .HasColumnType("integer");

                    b.Property<string>("Pagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdNoleggio");

                    b.HasIndex("IdArmadio");

                    b.HasIndex("IdChiave");

                    b.HasIndex("IdUtente");

                    b.HasIndex("Pagamento");

                    b.ToTable("NoleggioModel");
                });

            modelBuilder.Entity("armadieti2.Models.StatoArmadioModel", b =>
                {
                    b.Property<string>("StatoArmadio")
                        .HasColumnType("text");

                    b.HasKey("StatoArmadio");

                    b.ToTable("StatoArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.StatoChiaveModel", b =>
                {
                    b.Property<string>("StatoChiave")
                        .HasColumnType("text");

                    b.HasKey("StatoChiave");

                    b.ToTable("StatoChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.TipoPagamentoModel", b =>
                {
                    b.Property<string>("Pagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Pagamento");

                    b.ToTable("TipoPagamentoModel");
                });

            modelBuilder.Entity("armadieti2.Models.TipoUtenteModel", b =>
                {
                    b.Property<string>("TipoUtente")
                        .HasColumnType("text");

                    b.HasKey("TipoUtente");

                    b.ToTable("TipoUtenteModel");
                });

            modelBuilder.Entity("armadieti2.Models.UtenteModel", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdMonitor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomeDipartimento")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoUtente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUtente");

                    b.HasIndex("NomeDipartimento");

                    b.HasIndex("TipoUtente");

                    b.ToTable("UtenteModel");
                });

            modelBuilder.Entity("armadieti2.Models.ArmadioModel", b =>
                {
                    b.HasOne("armadieti2.Models.CategoriaArmadioModel", "CategoriaArmadioModel")
                        .WithMany()
                        .HasForeignKey("CategoriaArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.StatoArmadioModel", "StatoArmadioModel")
                        .WithMany()
                        .HasForeignKey("StatoArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaArmadioModel");

                    b.Navigation("StatoArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.ChiaveModel", b =>
                {
                    b.HasOne("armadieti2.Models.ArmadioModel", "ArmadioModel")
                        .WithMany()
                        .HasForeignKey("IdArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.StatoChiaveModel", "StatoChiaveModel")
                        .WithMany()
                        .HasForeignKey("StatoChiave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmadioModel");

                    b.Navigation("StatoChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.NoleggioModel", b =>
                {
                    b.HasOne("armadieti2.Models.ArmadioModel", "ArmadioModel")
                        .WithMany()
                        .HasForeignKey("IdArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.ChiaveModel", "ChiaveModel")
                        .WithMany()
                        .HasForeignKey("IdChiave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.UtenteModel", "UtenteModel")
                        .WithMany()
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.TipoPagamentoModel", "TipoPagamentoModel")
                        .WithMany()
                        .HasForeignKey("Pagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmadioModel");

                    b.Navigation("ChiaveModel");

                    b.Navigation("TipoPagamentoModel");

                    b.Navigation("UtenteModel");
                });

            modelBuilder.Entity("armadieti2.Models.UtenteModel", b =>
                {
                    b.HasOne("armadieti2.Models.DipartimentoModel", "DipartimentoModel")
                        .WithMany()
                        .HasForeignKey("NomeDipartimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.TipoUtenteModel", "TipoUtenteModel")
                        .WithMany()
                        .HasForeignKey("TipoUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DipartimentoModel");

                    b.Navigation("TipoUtenteModel");
                });
#pragma warning restore 612, 618
        }
    }
}
