// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using armadieti2.Models;

#nullable disable

namespace armadieti2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("armadieti2.Models.ArmadioModel", b =>
                {
                    b.Property<int>("IdArmadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArmadio"));

<<<<<<< HEAD
                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatoArmadio")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

=======
                    b.Property<string>("CategoriaArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.Property<string>("Piano")
                        .IsRequired()
                        .HasColumnType("text");

<<<<<<< HEAD
                    b.HasKey("IdArmadio");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdStatoArmadio");
=======
                    b.Property<string>("StatoArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdArmadio");

                    b.HasIndex("CategoriaArmadio");

                    b.HasIndex("StatoArmadio");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("ArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.CategoriaArmadioModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("CategoriaArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCategoria");
=======
                    b.Property<string>("CategoriaArmadio")
                        .HasColumnType("text");

                    b.HasKey("CategoriaArmadio");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("CategoriaArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.ChiaveModel", b =>
                {
                    b.Property<int>("IdChiave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChiave"));

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArmadio")
                        .HasColumnType("integer");

<<<<<<< HEAD
                    b.Property<int>("IdStatoChiave")
                        .HasColumnType("integer");
=======
                    b.Property<string>("StatoChiave")
                        .IsRequired()
                        .HasColumnType("text");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.HasKey("IdChiave");

                    b.HasIndex("IdArmadio");

<<<<<<< HEAD
                    b.HasIndex("IdStatoChiave");
=======
                    b.HasIndex("StatoChiave");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("ChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.DipartimentoModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdDipartimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDipartimento"));

                    b.Property<string>("NomeDipartimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdDipartimento");
=======
                    b.Property<string>("NomeDipartimento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NomeDipartimento");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("DipartimentoModel");
                });

            modelBuilder.Entity("armadieti2.Models.NoleggioModel", b =>
                {
                    b.Property<int>("IdNoleggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNoleggio"));

                    b.Property<decimal>("Cauzione")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArmadio")
                        .HasColumnType("integer");

                    b.Property<int>("IdChiave")
                        .HasColumnType("integer");

<<<<<<< HEAD
                    b.Property<int>("IdTipoPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("integer");

                    b.Property<int>("IdUtente")
                        .HasColumnType("integer");

=======
                    b.Property<int>("IdUtente")
                        .HasColumnType("integer");

                    b.Property<string>("Pagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.HasKey("IdNoleggio");

                    b.HasIndex("IdArmadio");

                    b.HasIndex("IdChiave");

<<<<<<< HEAD
                    b.HasIndex("IdTipoPagamento");

                    b.HasIndex("IdUtente");

=======
                    b.HasIndex("IdUtente");

                    b.HasIndex("Pagamento");

>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.ToTable("NoleggioModel");
                });

            modelBuilder.Entity("armadieti2.Models.StatoArmadioModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdStatoArmadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStatoArmadio"));

                    b.Property<string>("StatoArmadio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdStatoArmadio");
=======
                    b.Property<string>("StatoArmadio")
                        .HasColumnType("text");

                    b.HasKey("StatoArmadio");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("StatoArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.StatoChiaveModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdStatoChiave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStatoChiave"));

                    b.Property<string>("StatoChiave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdStatoChiave");
=======
                    b.Property<string>("StatoChiave")
                        .HasColumnType("text");

                    b.HasKey("StatoChiave");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("StatoChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.TipoPagamentoModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdTipoPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoPagamento"));

                    b.Property<string>("Pagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdTipoPagamento");
=======
                    b.Property<string>("Pagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Pagamento");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("TipoPagamentoModel");
                });

            modelBuilder.Entity("armadieti2.Models.TipoUtenteModel", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("IdTipoUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoUtente"));

                    b.Property<string>("TipoUtente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTipoUtente");
=======
                    b.Property<string>("TipoUtente")
                        .HasColumnType("text");

                    b.HasKey("TipoUtente");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("TipoUtenteModel");
                });

            modelBuilder.Entity("armadieti2.Models.UtenteModel", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

<<<<<<< HEAD
                    b.Property<int>("IdDipartimento")
                        .HasColumnType("integer");

=======
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.Property<string>("IdMonitor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

<<<<<<< HEAD
                    b.Property<int>("IdTipoUtente")
                        .HasColumnType("integer");

=======
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

<<<<<<< HEAD
                    b.HasKey("IdUtente");

                    b.HasIndex("IdDipartimento");

                    b.HasIndex("IdTipoUtente");
=======
                    b.Property<string>("NomeDipartimento")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoUtente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUtente");

                    b.HasIndex("NomeDipartimento");

                    b.HasIndex("TipoUtente");
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72

                    b.ToTable("UtenteModel_1");
                });

            modelBuilder.Entity("armadieti2.Models.ArmadioModel", b =>
                {
                    b.HasOne("armadieti2.Models.CategoriaArmadioModel", "CategoriaArmadioModel")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("IdCategoria")
=======
                        .HasForeignKey("CategoriaArmadio")
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.StatoArmadioModel", "StatoArmadioModel")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("IdStatoArmadio")
=======
                        .HasForeignKey("StatoArmadio")
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaArmadioModel");

                    b.Navigation("StatoArmadioModel");
                });

            modelBuilder.Entity("armadieti2.Models.ChiaveModel", b =>
                {
                    b.HasOne("armadieti2.Models.ArmadioModel", "ArmadioModel")
                        .WithMany()
                        .HasForeignKey("IdArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.StatoChiaveModel", "StatoChiaveModel")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("IdStatoChiave")
=======
                        .HasForeignKey("StatoChiave")
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmadioModel");

                    b.Navigation("StatoChiaveModel");
                });

            modelBuilder.Entity("armadieti2.Models.NoleggioModel", b =>
                {
                    b.HasOne("armadieti2.Models.ArmadioModel", "ArmadioModel")
                        .WithMany()
                        .HasForeignKey("IdArmadio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.ChiaveModel", "ChiaveModel")
                        .WithMany()
                        .HasForeignKey("IdChiave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD
                    b.HasOne("armadieti2.Models.TipoPagamentoModel", "TipoPagamentoModel")
                        .WithMany()
                        .HasForeignKey("IdTipoPagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

=======
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.HasOne("armadieti2.Models.UtenteModel", "UtenteModel")
                        .WithMany()
                        .HasForeignKey("IdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD
=======
                    b.HasOne("armadieti2.Models.TipoPagamentoModel", "TipoPagamentoModel")
                        .WithMany()
                        .HasForeignKey("Pagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                    b.Navigation("ArmadioModel");

                    b.Navigation("ChiaveModel");

                    b.Navigation("TipoPagamentoModel");

                    b.Navigation("UtenteModel");
                });

            modelBuilder.Entity("armadieti2.Models.UtenteModel", b =>
                {
                    b.HasOne("armadieti2.Models.DipartimentoModel", "DipartimentoModel")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("IdDipartimento")
=======
                        .HasForeignKey("NomeDipartimento")
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("armadieti2.Models.TipoUtenteModel", "TipoUtenteModel")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("IdTipoUtente")
=======
                        .HasForeignKey("TipoUtente")
>>>>>>> fae79dd8d590fb61295b7371cc064b6c93044b72
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DipartimentoModel");

                    b.Navigation("TipoUtenteModel");
                });
#pragma warning restore 612, 618
        }
    }
}
